#!/usr/bin/env bash
# 03-sway — deploy Aura's sway + Waybar configs, swap display managers.
#
# Replaces 03-hyprland.sh (task 001b: sway over Hyprland). Also brings
# up greetd+tuigreet (autologin on the test VM, tuigreet after logout),
# keeps the zram config versioned, and retires sddm once greetd is live.
# Safe to re-run.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    exec sudo -E "$(readlink -f "$0")" "$@"
fi

REPO="${REPO_DIR:-$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)}"
user="${AURA_USER:?AURA_USER is not set — run this through install.sh}"
home="$(getent passwd "$user" | cut -d: -f6)"
if [[ ! -d $home ]]; then
    echo "03-sway: no home directory for $user" >&2
    exit 1
fi

cfg="$home/.config"
# install -d only gives the LAST level to the user: on a fresh home every
# parent must be listed, or ~/.config ends up root's (first-boot test).
install -d -o "$user" -g "$user" "$cfg" "$cfg/sway" "$cfg/sway/config.d" "$cfg/waybar" \
    "$home/.local" "$home/.local/share"

put() { # put <src> <dst> — install only when it differs, say so either way
    if cmp -s "$1" "$2" 2>/dev/null; then
        echo "03-sway: up to date: $2"
    else
        install -m 644 -o "$user" -g "$user" "$1" "$2"
        echo "03-sway: wrote $2"
    fi
}

put "$REPO/config/sway/config" "$cfg/sway/config"
put "$REPO/config/sway/config.d/10-binds.conf" "$cfg/sway/config.d/10-binds.conf"
put "$REPO/config/sway/config.d/15-fkeys.conf" "$cfg/sway/config.d/15-fkeys.conf"
put "$REPO/config/sway/config.d/05-aura-term.conf" "$cfg/sway/config.d/05-aura-term.conf"
# voice (dic), aura-pulse, powerboard (install/09) — keybinds + launcher
put "$REPO/config/sway/config.d/20-dusan-apps.conf" "$cfg/sway/config.d/20-dusan-apps.conf"
put "$REPO/config/sway/config.d/20-mouse.conf" "$cfg/sway/config.d/20-mouse.conf"
put "$REPO/config/sway/config.d/30-idle.conf" "$cfg/sway/config.d/30-idle.conf"
put "$REPO/config/waybar/config.jsonc" "$cfg/waybar/config.jsonc"
put "$REPO/config/waybar/style.css" "$cfg/waybar/style.css"
install -d -o "$user" -g "$user" "$cfg/waybar/assets"
for a in "$REPO"/config/waybar/assets/*.png; do put "$a" "$cfg/waybar/assets/$(basename "$a")"; done
# look.css is generated by aura-look; a fresh user gets the default once.
[[ -f $cfg/waybar/look.css ]] || put "$REPO/config/waybar/look.css" "$cfg/waybar/look.css"
install -d -o "$user" -g "$user" "$cfg/fuzzel" "$home/.local/share/applications"
put "$REPO/config/fuzzel/fuzzel.ini" "$cfg/fuzzel/fuzzel.ini"
# Theme files are generated; make sure a fresh user has the default.
# Aura adOS wallpaper ships in /usr/share/aura-os/wallpapers (the picker
# lists it); a fresh user gets it as the background.
for w in "$REPO"/assets/wallpapers/*; do
    cmp -s "$w" "/usr/share/aura-os/wallpapers/$(basename "$w")" \
        || { install -Dm644 "$w" "/usr/share/aura-os/wallpapers/$(basename "$w")"; echo "03-sway: installed wallpaper $(basename "$w")"; }
done
if [[ ! -f $cfg/waybar/theme.css ]]; then
    sudo -u "$user" env HOME="$home" AURA_OS_REPO="$REPO" "$REPO/bin/aura-os-theme" apply purplerain >/dev/null
    echo "03-sway: applied default theme purplerain"
    install -d -o "$user" -g "$user" "$cfg/sway/config.d"
    printf '# aura-os-wallpaper\noutput * bg "/usr/share/aura-os/wallpapers/aura-ados.jpg" fill\n' \
        > "$cfg/sway/config.d/60-wallpaper.conf"
    chown "$user:$user" "$cfg/sway/config.d/60-wallpaper.conf"
    echo "03-sway: default wallpaper Aura adOS"
fi
# launcher entries (Aura Pulse; powerboard's comes from its cmake install)
for f in "$REPO"/config/applications/*.desktop; do   # hide dependency clutter from the launcher
    put "$f" "$home/.local/share/applications/$(basename "$f")"
done

# Stale SDDM autologin from task 001 — greetd replaces it.
if [[ -e /etc/sddm.conf.d/10-aura.conf ]]; then
    rm -f /etc/sddm.conf.d/10-aura.conf
    echo "03-sway: removed stale /etc/sddm.conf.d/10-aura.conf (superseded by greetd)"
fi

# greetd: the greeter user, the config, the service.
if [[ -f /usr/lib/systemd/system/greetd.service ]]; then
    if ! id greeter >/dev/null 2>&1; then
        useradd --system --home-dir /var/lib/greetd --create-home \
            --shell /usr/bin/nologin greeter
        echo "03-sway: created system user 'greeter'"
    fi
    want="$(sed "s/@AURA_USER@/$user/" "$REPO/config/greetd/config.toml")"
    if [[ "$(cat /etc/greetd/config.toml 2>/dev/null)" != "$want" ]]; then
        printf '%s\n' "$want" > /etc/greetd/config.toml
        echo "03-sway: wrote /etc/greetd/config.toml"
    else
        echo "03-sway: up to date: /etc/greetd/config.toml"
    fi
else
    echo "03-sway: greetd is not installed — skipping the display manager swap" >&2
fi

# zram swap (task 001b). Keep the config versioned so it is inspectable.
zram_conf=/etc/systemd/zram-generator.conf
want_zram="$(cat "$REPO/config/zram/zram-generator.conf")"
if [[ "$(cat "$zram_conf" 2>/dev/null)" != "$want_zram" ]]; then
    printf '%s\n' "$want_zram" > "$zram_conf"
    systemctl daemon-reload
    systemctl restart systemd-zram-setup@zram0.service 2>/dev/null || true
    echo "03-sway: wrote $zram_conf (zram0 (re)started)"
else
    echo "03-sway: up to date: $zram_conf"
fi

# VM tunables for zram swap: kernel defaults assume slow disk swap, zram is
# in-RAM (zstd, no seek penalty) so pages can go out earlier and come back
# cheap. Deployed to /usr/lib so a future /etc drop-in can always override.
sysctl_conf="$REPO/config/zram/sysctl.conf"
sysctl_dst=/usr/lib/sysctl.d/70-aura-zram.conf
if ! cmp -s "$sysctl_conf" "$sysctl_dst"; then
    install -Dm644 "$sysctl_conf" "$sysctl_dst"
    sysctl --system >/dev/null
    echo "03-sway: installed $sysctl_dst (applied)"
else
    echo "03-sway: up to date: $sysctl_dst"
fi

# Display manager swap: stop and disable sddm first, then greetd; sway
# comes up on vt1 (autologin via [initial_session] on this VM).
if [[ -f /usr/lib/systemd/system/greetd.service ]]; then
    if systemctl is-active --quiet sddm; then
        systemctl stop sddm
        echo "03-sway: stopped sddm"
    fi
    if systemctl is-enabled --quiet sddm 2>/dev/null; then
        systemctl disable sddm
        echo "03-sway: disabled sddm"
    fi
    if ! systemctl is-enabled --quiet greetd 2>/dev/null; then
        systemctl enable greetd
        echo "03-sway: enabled greetd"
    fi
    # The first boot (aura-os-firstboot) owns tty1 until it reboots;
    # greetd starts on that reboot instead.
    if [[ -z ${AURA_FIRSTBOOT:-} ]] && ! systemctl is-active --quiet greetd; then
        systemctl start greetd
        echo "03-sway: started greetd — the session comes up on vt1"
    fi

    # sddm is retired once greetd is the display manager; xorg-server
    # exists here only for sddm. xorg-xwayland stays installed: task 001b
    # keeps Xwayland available, lazily. Removal goes through aura-os-remove.
    if pacman -Qq sddm >/dev/null 2>&1 && [[ -x $REPO/bin/aura-os-remove ]]; then
        "$REPO/bin/aura-os-remove" sddm xorg-server
    fi
fi
